### ISSUE TITLE
The design feels kinda off

### ISSUE THREAD

**Issue by ooade** [Oluwaseunus/challenge-1#2]
- The fonts feels larger than they should
- You could apply a google font, using Roboto or Nunito
- `main__header` has like 2 bottom border? The other is applied by the after pseudo element.
- The edit div's are not well rounded, because they don't save same width and height.
- 1px of border on the inputs is fine, and the size could go a little bit longer.
- The button width should be more than the height based on the figma.
- The start of `profile_bg` should also be the start of your inputs, same as end. So you could set the width to that of `profile_bg`, and you'd be fine since you have `align_items: space-between`.
- Clicking the `edit edit__bottom` should be the one to trigger the picture menu. Besides the menu could be an absolute position based on it's trigger.

Can you fix those?

**Comment by Oluwaseunus** [comment]
Fixing them now...

The after pseudo element of the `main__header` is what makes a portion of the bottom border invisible. It's 1px thick.

> Clicking the edit edit__bottom should be the one to trigger the picture menu. Besides the menu could be an absolute position based on it's trigger.

That's how it is on my local server. Is there anything in the deployment that could be triggering a difference in render?

**Comment by ooade** [comment]
There's no need for the after pseudo element there. Send your updates, waiting for them. 

Thanks.

**Comment by Oluwaseunus** [comment]
They're available now, [here](https://oluwaseunus.github.io/challenge-1/)

**Comment by ooade** [comment]
Seen:
- The 2 borders are still there
- The font sizes are quite larger than they should be
- The input border bottom are still 2px's each
- The `edit edit__bottom` still doesn't have an onclick handler that toggles the menu shown or hidden

**Comment by Oluwaseunus** [comment]
The second bottom border (for the "after" pseudo element, is to make the
the bottom border of the EDIT PROFILE header look incomplete. Notice that
the header does not appear to completely reach the left side. I've
commented it out.

Could you tell me the particular place where the font is too big? I think
reducing the font size any further might make it too small. I've tried
viewing the page on a lower resolution screen and it looks mostly the same.

The 2px bottom border on the inputs is what makes up their underline. The
inputs in the mockup did not have the usual border around them so this one
doesn't too.

I have fixed the issue with the button showing the options.

**Comment by ooade** [comment]
Here's the screenshot:
![Screenshot from 2019-05-03 15-58-24](https://user-images.githubusercontent.com/11811904/57146823-27c5d080-6dbe-11e9-8a38-96697f562b56.png)

Here's like an improved version of the original design:
![Screenshot from 2019-05-03 16-15-13](https://user-images.githubusercontent.com/11811904/57147059-a6bb0900-6dbe-11e9-9d22-b58da37b4f0c.png)

Notice the font sizes. To get this properly you'd have to zoom the figma to 100%
- The selection tags, as well, should be without background
- The menu should have a curved border radius
- The menu should have a padding
- The input border should still be 1px

**Comment by Oluwaseunus** [comment]
I just pushed some changes.

- Added the menu padding and border radius
- Reduced input border to 1px
- Reduced font size

However, the selection tags have no specified background. Only what's coming from the user agent stylesheet.

**Comment by ooade** [comment]
The selection tags should have changed as well, like so:
![Screenshot from 2019-05-03 19-21-23](https://user-images.githubusercontent.com/11811904/57157460-ac254d00-6dd8-11e9-9640-199d07224ca4.png)

#EEE is a better grey variant compared to what was used
![Screenshot from 2019-05-03 19-26-41](https://user-images.githubusercontent.com/11811904/57157806-9fedbf80-6dd9-11e9-9b0a-6a938db838dd.png)
It's all good.

The Edit Profile text should be a bit smaller as well.

Can you try fixing those and kindly switch to using Raleway font?
And lastly, try to make the whole page responsive
Right now it looks like:
![Screenshot from 2019-05-03 19-31-13](https://user-images.githubusercontent.com/11811904/57157960-0a9efb00-6dda-11e9-8fc3-0e25a6470a72.png)
and:
![Screenshot from 2019-05-03 19-31-17](https://user-images.githubusercontent.com/11811904/57158009-30c49b00-6dda-11e9-9870-e43a53e93437.png)

You've tried, really. Just try fixing those and get back to me ASAP.
Thanks :)

**Comment by ooade** [comment]
This is final, so try to make the necessary adjustment. When you're done, feel free to tag me and close the issue.

**Comment by Oluwaseunus** [comment]
I've fixed the issues, @ooade 

The select background must be a linux thing because it didn't show on my windows machine. Nevertheless, that's fixed, and I've made the entire page responsive. Thanks for your feedback.

**Comment by ooade** [comment]
cc @mayordwells
